name: TruffleRuby Build

on:
  push:
    branches:
    - master
  pull_request:

jobs:
  jruby-test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        core_ext: ["gem", "generated"]
    env:
      CORE_EXT: ${{ matrix.core_ext }}
    steps:
    - uses: actions/checkout@v2
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: truffleruby
    - name: Download MSpec
      run: |
        git clone https://github.com/ruby/mspec.git mspec
    - uses: actions/cache@v1
      with:
        path: vendor/bundle
        key: bundle-use-ruby-${{ matrix.os }}-${{ matrix.ruby }}-${{ hashFiles('**/Gemfile') }}-${{ hashFiles('**/*.gemspec') }}
        restore-keys: |
          bundle-use-ruby-${{ matrix.os }}-${{ matrix.ruby }}-
    - name: Install deps
      env:
        BUNDLE_RUBYGEMS__PKG__GITHUB__COM: "palkan:${{ secrets.GITHUB_TOKEN }}"
      run: |
        bundle config path vendor/bundle
        bundle install --jobs 4 --retry 3
    - name: Run MSpec
      run: |
        bundle exec mspec/bin/mspec :cli
